@startuml UC_diagram
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 11
skinparam backgroundColor #FEFEFE
left to right direction

title Use Case diagram – C3 schopnosti, požadavky a omezení (RQU007)

actor "Uživatel" as U

rectangle "RQU007 C3 schopnosti + Požadavky" {
    usecase "UC053 Stáhnout poster\nC3 schopností" as UC053
    usecase "UC054 Seznam\npožadavků na MV" as UC054
    usecase "UC055 Seznam\nomezení MV" as UC055
}

U --> UC053
U --> UC054
U --> UC055

@enduml
