@startuml UC_diagram
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 11
skinparam backgroundColor #FEFEFE
left to right direction

title Use Case diagram – C3 schopnosti, požadavky a omezení (RQU007)

actor "Uživatel" as U

rectangle "RQU007 C3 schopnosti + Požadavky" {
    usecase "UC001 Stáhnout poster\nC3 schopností" as UC001
    usecase "UC002 Seznam\npožadavků na MV" as UC002
    usecase "UC003 Seznam\nomezení MV" as UC003
}

U --> UC001
U --> UC002
U --> UC003

@enduml
