@startuml UC_diagram
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 11
skinparam backgroundColor #FEFEFE
left to right direction

title Use Case diagram – Řešení evidence osob na MV a v misích (RQU009)

actor "Uživatel" as U

rectangle "RQU009 Evidence osob (návrh)" {
    usecase "UC061 Zobrazit a\nvyhledat osoby" as UC061
    usecase "UC062 Vytvořit /\nupravit osobu" as UC062
    usecase "UC063 Obsadit pozici\nna MV osobou" as UC063
    usecase "UC064 Zapojit osobu\ndo mise" as UC064
}

U --> UC061
U --> UC062
U --> UC063
U --> UC064

@enduml
