#!/usr/bin/env python3
"""Generuje data.js pro offline (file://) prohlížení analýzy v HTML vieweru.

Použití:
    python build_data.py

Čte manifest.json a všechny odkazované MD a PUML soubory,
výstupem je data.js ve stejném adresáři.
"""
import json, os, sys

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    with open("manifest.json", "r", encoding="utf-8") as f:
        manifest = json.load(f)

    files = {}

    # README.md (overview tab)
    if os.path.exists("README.md"):
        with open("README.md", "r", encoding="utf-8") as f:
            files["README.md"] = f.read()

    # Existing elements overlay (optional)
    if os.path.exists("existing_elements.json"):
        with open("existing_elements.json", "r", encoding="utf-8") as f:
            files["existing_elements.json"] = f.read()

    # MD soubory z tabs
    for tab in manifest.get("tabs", []):
        path = tab["file"]
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                files[path] = f.read()

    # PUML soubory
    for tab_id, puml_list in manifest.get("plantuml", {}).items():
        for path in puml_list:
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    files[path] = f.read()

    data = {"manifest": manifest, "files": files}

    with open("data.js", "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_data.py – do not edit manually\n")
        f.write("window.__ANALYSIS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=None)
        f.write(";\n")

    print(f"data.js vygenerován ({len(files)} souborů, {os.path.getsize('data.js')//1024} KB)")

if __name__ == "__main__":
    main()
