@startuml UC_diagram
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 11
skinparam backgroundColor #FEFEFE
left to right direction

title Use Case diagram – Katalog služeb (C3 Taxonomy) (RQU005)

actor "Uživatel" as U

rectangle "RQU005 Katalog služeb" {
    usecase "UC047 Přehled\nkatalogu služeb" as UC047
    usecase "UC048 Zobrazit a vyhledat\nprvky kategorie" as UC048
    usecase "UC049 Vytvořit\nCIS prvek" as UC049
}

U --> UC047
U --> UC048
U --> UC049

@enduml
