@startuml UC_diagram
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 11
skinparam backgroundColor #FEFEFE
left to right direction

title Use Case diagram – Společné a bojové funkce + PI (RQU006)

actor "Uživatel" as U

rectangle "RQU006 Funkce SVŘ" {
    usecase "UC050 Přehled\nspolečných funkcí" as UC050
    usecase "UC051 Přehled\nbojových funkcí" as UC051
    usecase "UC052 Vazba na FMN\nprocedurální instrukce" as UC052
}

U --> UC050
U --> UC051
U --> UC052

@enduml
